<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API Version' => 'API Version',
    'Alt text' => 'Alt text',
    'Are you sure you want to remove this webhook?' => 'Sind Sie sicher, dass Sie diesen Webhook löschen wollen?',
    'Barcode (ISBN, UPC, GTIN, etc.)' => 'Barcode (ISBN, UPC, GTIN, etc.)',
    'Compare at price' => 'Vergleichspreis',
    'Description' => 'Beschreibung',
    'Event' => 'Event',
    'Format' => 'Format',
    'Height' => 'Höhe',
    'Image' => 'Bild',
    'Inventory' => 'Inventar',
    'Inventory management' => 'Inventarverwaltung',
    'Inventory policy' => 'Inventarregel',
    'Manage Shopify products' => 'Shopify Produkte verwalten',
    'Manage Shopify webhooks' => 'Shopify Webhooks verwalten',
    'New Product' => 'Neues Produkt',
    'Option 1' => 'Option 1',
    'Option 2' => 'Option 2',
    'Option 3' => 'Option 3',
    'Position' => 'Position',
    'Price' => 'Preis',
    'Product' => 'Produkt',
    'Product created' => 'Produkt erstellt',
    'Product deleted' => 'Produkt gelöscht',
    'Product updated' => 'Produkt aktualisiert',
    'Products' => 'Produkte',
    'Quantity' => 'Anzahl',
    'Reload Webhooks' => 'Webhooks neu laden',
    'Reload Products' => 'Produkte neu laden',
    'SKU (Stock Keeping Unit)' => 'Artikelnummer (Stock Keeping Unit)',
    'Shopify' => 'Shopify',
    'Shopify Admin API secret key must be set to use webhooks.' => 'Der geheimer API-Schlüssel (bei Shopify unter Apps > API-Anmeldedaten) muss gesetzt sein, um Webhooks zu nutzen.',
    'Shopify slug' => 'Shopify slug',
    'Taxable' => 'Steuerpflichtig',
    'The product was updated via Shopify.' => 'Das Produkt wurde über Shopify aktualisiert.',
    'The webhook "{topic}" was created.' => 'Der Webhook "{topic}" wurde erstellt.',
    'The webhook "{topic}" was skipped.' => 'Der Webhook "{topic}" wurde übersprungen.',
    'The webhook was deleted.' => 'Der Webhook wurde gelöscht.',
    'Title' => 'Titel',
    'Type' => 'Typ',
    'URL' => 'URL',
    'Variant' => 'Variante',
    'Variants' => 'Varianten',
    'Vendor' => 'Anbieter',
    'View Products' => 'Produkte anzeigen',
    'View Webhooks' => 'Webhooks anzeigen',
    'Webhooks' => 'Webhooks',
    'Weight' => 'Gewicht',
    'Weight (grams)' => 'Gewicht (Gramm)',
    'Weight unit' => 'Gewichtseinheit',
];
