<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API Version' => '',
    'All products updated via Shopify.' => '',
    'Alt text' => '',
    'Are you sure you want to remove this webhook?' => '',
    'Barcode (ISBN, UPC, GTIN, etc.)' => '',
    'Compare at price' => '',
    'Description' => '',
    'Event' => '',
    'Format' => '',
    'Height' => '',
    'Image' => '',
    'Install Webhooks' => '',
    'Inventory' => '',
    'Inventory policy' => '',
    'Inventory tracking' => '',
    'Manage Shopify products' => '',
    'Manage Shopify webhooks' => '',
    'New Product' => '',
    'Option 1' => '',
    'Option 2' => '',
    'Option 3' => '',
    'Position' => '',
    'Price' => '',
    'Product' => '',
    'Products' => '',
    'Quantity' => '',
    'Reload Products' => '',
    'SKU (Stock Keeping Unit)' => '',
    'Shopify' => '',
    'Shopify Admin API secret key must be set to use webhooks.' => '',
    'Shopify slug' => '',
    'Taxable' => '',
    'The product was deleted because it was not found on Shopify anymore.' => '',
    'The product was updated via Shopify.' => '',
    'The webhook "{topic}" was created.' => '',
    'The webhook was deleted.' => '',
    'Title' => '',
    'Type' => '',
    'URL' => '',
    'Variant' => '',
    'Variants' => '',
    'Vendor' => '',
    'View Products' => '',
    'View Webhooks' => '',
    'Webhooks' => '',
    'Weight' => '',
    'Weight (grams)' => '',
    'Weight unit' => '',
];
